config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :orders

  resource :checkout do
    get :return_callback
    get :cancel_callback
    get :notify_callback
  end

  root 'orders#new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  validates :name, presence: true
  validates :phone_number, presence: true
  validates :shipping_address, presence: true
  validates :quantity, presence: true
  validates :bank_account_number, presence: true
  validates :bank_name, presence: true
  validates :code, presence: true

  before_validation :set_code, on: :create

  enum payment_status: { pending: 0, processing: 1, cancelled: 2, paid: 3 }

  def price
    quantity * 339000
  end

  def currency
    'vnd'
  end

  def tax
    0
  end

  def discount
    0
  end

  def fee_cal
    0
  end

  def fee_shipping
    0
  end

  def buyer_info
    [name, phone_number].join(" - ")
  end

  def description
    "The Khải Huyền - Số lượng: #{quantity}"
  end

  private

  def set_code
    self.code = SecureRandom.uuid
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  layout 'checkout'

  def cancel_callback
    @order = Order.find_by(code: params[:order_code])

    if @order
      @order.update(payment_status: :cancelled)
    else
      render :file => 'public/404.html', :status => :not_found, :layout => false
    end
  end

  def notify_callback
    @order = Order.find_by(code: params[:order_code])

    if NganLuong::Payment.valid_return_request?(params[:transaction_info], params[:order_code], params[:price], params[:payment_id], params[:payment_type], params[:error_text], params[:secure_code])
      @order.update(payment_status: :paid)
    end

    render plain: "1"
  end

  def return_callback
    @order = Order.find_by(code: params[:order_code])

    if NganLuong::Payment.valid_return_request?(params[:transaction_info], params[:order_code], params[:price], params[:payment_id], params[:payment_type], params[:error_text], params[:secure_code])
      @order.update(payment_status: :paid)
    else
      redirect_to cancel_callback_checkout_path(order_code: params[:order_code])
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @order = Order.find_by(code: params[:id])

    if @order.nil?
      render :file => 'public/404.html', :status => :not_found, :layout => false
    else
      @checkout_url = NganLuong::Payment.get_checkout_url(
        order_code: @order.code,
        price: @order.price,
        currency: @order.currency,
        quantity: @order.quantity,
        tax: @order.tax,
        discount: @order.discount,
        fee_cal: @order.fee_cal,
        fee_shipping: @order.fee_shipping,
        buyer_info: @order.buyer_info,
        order_description: @order.description,
        cancel_url: cancel_callback_checkout_url(order_code: @order.code),
        return_url: return_callback_checkout_url,
        notify_url: notify_callback_checkout_url,
      )
    end
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order.code), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def order_params
    params.require(:order).permit(:name, :phone_number, :shipping_address, :quantity, :bank_account_number, :bank_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def banks
    [
      "",
      "VCB - NH TMCP Ngoai Thuong Viet Nam",
      "ACB - NH Thuong Mai Co Phan A Chau",
      "BIDV - NH TMCP Dau tu va Phat trien Viet Nam",
      "VIETBANK - NH TMCP Viet Nam Thuong Tin",
      "TCB - NH TMCP Ky thuong Viet Nam",
      "STB - NH TMCP Sai Gon Thuong Tin",
      "VPB - NH TMCP Viet Nam Thinh Vuong",
      "EIB - NH TMCP Xuat nhap khau Viet Nam",
      "ABB - NH TMCP An Binh",
      "AGRIBANK - NH NN Va PTNT Viet Nam",
      "BAB - NH TMCP Bac A",
      "BVB - NH TMCP Bao Viet",
      "CBB - NH TM TNHH MTV Xay Dung Viet Nam",
      "CIMB - NH TNHH MTV CIMB",
      "COOPBANK - NH Hop tac xa Viet Nam",
      "DBS - NH DBS chi nhanh HCM",
      "DOB - NH TMCP Dong A",
      "GPB - NH TM TNHH MTV Dau Khi Toan Cau",
      "HDB - NH TMCP Phat Trien Thanh Pho Ho Chi Minh",
      "HLB - NH TNHH MTV Hongleong Viet Nam",
      "HSBC - Ngan hang TNHH MTV HSBC (Viet Nam)",
      "IBK - NH IBK - chi nhanh HCM",
      "IBK - NH IBK - chi nhanh Ha Noi",
      "ICB - NH TMCP Cong Thuong Viet Nam",
      "IVB - NH TNHH Indovina",
      "KBHCM - Kookmin Chi nhanh Thanh pho Ho Chi Minh",
      "KBHN - Kookmin Chi nhanh Ha Noi",
      "KEB Hana - Chi nhanh Ha Noi",
      "KEB Hana - Chi nhanh Thanh pho Ho Chi Minh",
      "KLB - NH TMCP Kien Long",
      "KSK - Dai chung TNHH Kasikornbank - Chi nhanh TP. HCM",
      "LPB - NH TMCP Buu Dien Lien Viet",
      "MAFC - CTY Tai chinh TNHH MTV Mirae Asset (Viet Nam)",
      "MB - NH TMCP Quan Doi",
      "MSB - NH TMCP Hang Hai Viet Nam",
      "NAB - NH TMCP Nam A",
      "NCB - NH TMCP Quoc Dan",
      "NH TMCP Phuong Dong (Liobank)",
      "NONGHYUP - Chi nhanh HN",
      "OCB - NH TMCP Phuong Dong",
      "Oceanbank - NH TMCP Dai Duong",
      "PBVN - NH TNHH MTV Public Viet Nam",
      "PGB - NH TMCP Xang Dau Petrolimex",
      "PVCB - NH TMCP Dai Chung Viet Nam",
      "SCB - NH TMCP Sai Gon",
      "SEAB - NH TMCP Dong Nam A",
      "SGB - NH TMCP Sai Gon Cong Thuong",
      "SHB - NH TMCP Sai Gon - Ha Noi",
      "SHBVN - NH TNHH MTV Shinhan Viet Nam",
      "TMCP Viet Nam Thinh Vuong - Ngan hang so CAKE by VPBank",
      "TMCP Viet Nam Thinh Vuong - Ngan hang so Ubank by VPBank",
      "TNHH MTV Standard Chartered Bank (Vietnam) Limited",
      "TPB - NH TMCP Tien Phong",
      "Timo by Ban Viet Bank - Ngân hàng số Timo",
      "UMEE - Ngan hang so UMEE by Kienlongbank",
      "UOB - NH TNHH MTV United Overseas Bank",
      "VAB - NH TMCP Viet A",
      "VBSP - Ngan hang Chinh sach Xa hoi",
      "VCCB - NH TMCP Ban Viet",
      "VIB - NH TMCP Quoc te Viet Nam",
      "VNPT Money - TT DV TC so VNPT - CN Tong cong ty truyen thong",
      "VRB - NH Lien Doanh Viet Nga",
      "Viettel Money - TCT DV so Viettel - CN Tap doan CN VT Quan doi",
      "WOO - NH Wooribank"
    ].sort
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/checkouts/cancel_callback.html.erb
<div>
  <p class="p-2" >Thanh toán thất bại.</p>
</div>

app/views/checkouts/new.html.erb
<div>
  <%= link_to 'Click here to checkout', @checkout_url %>
</div>

app/views/checkouts/return_callback.html.erb
<div>
  <p class="p-2" >Thanh toán thành công.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Khải Huyền</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <meta property="og:type" content="website">
    <meta property="og:title" content="The Khải Huyền">
    <meta property="og:description" content="Đặt mua sách The Khải Huyền">
    <meta property="og:image" content="<%= asset_path('order-bg.jpg') %>">
    <meta property="og:url" content="https://thekhaihuyen.com">
    <meta property="og:site_name" content="The Khải Huyền">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-[url('order-bg.jpeg')] bg-cover">
    <main class="p-8">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/checkout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Khải Huyền</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main style="padding: 8px">
      <%= yield %>
    </main>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, class: "px-6 py-4 bg-slate-800 bg-opacity-80 rounded") do |form| %>
  <div class="mb-4">
    <%= form.label :name, style: "display: block", class: 'text-white text-sm' %>
    <%= form.text_field :name, class: "w-full #{order.errors[:name].present? ? 'border-red-500' : ''}" %>
    <% if order.errors[:name].present? %>
      <div class="text-red-500 text-sm">
        <%= order.errors.full_messages_for(:name).first  %>
      </div>
    <% end %>
  </div>

  <div class="mb-4">
    <%= form.label :phone_number, style: "display: block", class: 'text-white text-sm' %>
    <%= form.text_field :phone_number, class: "w-full #{order.errors[:phone_number].present? ? 'border-red-500' : ''}" %>
    <% if order.errors[:phone_number].present? %>
      <div class="text-red-500">
        <%= order.errors.full_messages_for(:phone_number).first  %>
      </div>
    <% end %>
  </div>

  <div class="mb-4">
    <%= form.label :shipping_address, style: "display: block", class: 'text-white text-sm' %>
    <%= form.text_field :shipping_address, class: "w-full #{order.errors[:shipping_address].present? ? 'border-red-500' : ''}" %>
    <% if order.errors[:shipping_address].present? %>
      <div class="text-red-500 text-sm">
        <%= order.errors.full_messages_for(:shipping_address).first  %>
      </div>
    <% end %>
  </div>

  <div class="mb-4">
    <%= form.label :quantity, style: "display: block", class: 'text-white text-sm' %>
    <%= form.select :quantity, options_for_select([1, 2, 3, 4, 5]), {}, { class: "w-full #{order.errors[:quantity].present? ? 'border-red-500' : ''}" } %>
    <% if order.errors[:quantity].present? %>
      <div class="text-red-500 text-sm">
        <%= order.errors.full_messages_for(:quantity).first  %>
      </div>
    <% end %>
  </div>

  <div class="mb-4">
    <%= form.label :bank_account_number, style: "display: block", class: 'text-white text-sm' %>
    <%= form.text_field :bank_account_number, class: "w-full #{order.errors[:bank_account_number].present? ? 'border-red-500' : ''}" %>
    <% if order.errors[:bank_account_number].present? %>
      <div class="text-red-500 text-sm">
        <%= order.errors.full_messages_for(:bank_account_number).first  %>
      </div>
    <% end %>
  </div>

  <div class="mb-4">
    <%= form.label :bank_name, style: "display: block", class: 'text-white text-sm' %>
    <%= form.select :bank_name, options_for_select(banks), {}, { class: "w-full #{order.errors[:bank_name].present? ? 'border-red-500' : ''}" } %>
    <% if order.errors[:bank_name].present? %>
      <div class="text-red-500 text-sm">
        <%= order.errors.full_messages_for(:bank_name).first  %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.button t('.book_now'), type: :submit, class: 'w-full btn-primary uppercase py-4 bg-slate-500 text-white' %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>" class="px-6 py-4 bg-slate-800 bg-opacity-80 rounded text-white">
  <p class='uppercase text-center font-bold text-lg py-4'>Xác nhận đơn hàng</p>

  <p class="pb-1">
    <strong><%= Order.human_attribute_name(:name) %>:</strong>
    <%= order.name %>
  </p>

  <p class="pb-1">
    <strong><%= Order.human_attribute_name(:phone_number) %>:</strong>
    <%= order.phone_number %>
  </p>

  <p class="pb-1">
    <strong><%= Order.human_attribute_name(:shipping_address) %>:</strong>
    <%= order.shipping_address %>
  </p>

  <p class="pb-1">
    <strong><%= Order.human_attribute_name(:quantity) %>:</strong>
    <%= order.quantity %>
  </p>

  <p class="pb-1">
    <strong><%= Order.human_attribute_name(:bank_account_number) %>:</strong>
    <%= order.bank_account_number %>
  </p>

  <p class="pb-1">
    <strong><%= Order.human_attribute_name(:bank_name) %>:</strong>
    <%= order.bank_name %>
  </p>

  <p class="pb-1">
    <strong><%= t('.total') %>:</strong>
    <%= number_to_currency(order.price, unit: "VNĐ", format: "%n %u", delimiter: ".", separator: ",", precision: 0) %>
  </p>

  <p class="py-8 pb-4 text-center">
    <%= link_to 'Thanh toán', @checkout_url, class: 'w-full btn-primary uppercase py-4 bg-slate-500 text-white' %>
  </p>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<div class="md:w-[32rem] mx-auto">
  <h1 class="text-center pb-4 font-bold text-3xl">The Khải Huyền</h1>
  <%= render "form", order: @order %>
</div>

app/views/orders/show.html.erb
<%= render @order %>